image:
  repository: ferityuksel/demoideasoft
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: symfony-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources: {}
